// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A numerology analysis AI agent.
 *
 * - aiNumerologyAnalysis - A function that handles the numerology analysis process.
 * - AiNumerologyAnalysisInput - The input type for the aiNumerologyAnalysis function.
 * - AiNumerologyAnalysisOutput - The return type for the aiNumerologyAnalysis function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AiNumerologyAnalysisInputSchema = z.object({
  name: z.string().describe('The name of the person.'),
  dateOfBirth: z.string().describe('The date of birth of the person (YYYY-MM-DD).'),
  language: z.string().optional().describe("The language for the analysis (e.g., 'English', 'Hindi')."),
});
export type AiNumerologyAnalysisInput = z.infer<typeof AiNumerologyAnalysisInputSchema>;

const AiNumerologyAnalysisOutputSchema = z.object({
  lifePathNumber: z.object({
    number: z.number().describe('The Life Path Number.'),
    analysis: z.string().describe('A detailed analysis of the Life Path Number and its meaning for the person.'),
  }),
  destinyNumber: z.object({
      number: z.number().describe('The Destiny (or Expression) Number.'),
      analysis: z.string().describe('A detailed analysis of the Destiny Number and what it reveals.'),
  }),
  soulUrgeNumber: z.object({
      number: z.number().describe('The Soul Urge Number.'),
      analysis: z.string().describe("A detailed analysis of the Soul Urge Number and the person's inner desires."),
  }),
  personalityNumber: z.object({
      number: z.number().describe('The Personality Number.'),
      analysis: z.string().describe("A detailed analysis of the Personality Number and how the person appears to others."),
  }),
  birthDayNumber: z.object({
      number: z.number().describe('The Birth Day Number.'),
      analysis: z.string().describe('A detailed analysis of the Birth Day Number and its influence.'),
  }),
  maturityNumber: z.object({
      number: z.number().describe('The Maturity Number.'),
      analysis: z.string().describe('A detailed analysis of the Maturity Number and what it suggests for the person\'s later life.'),
  }),
  personalYearNumber: z.object({
      number: z.number().describe('The Personal Year Number.'),
      analysis: z.string().describe('An analysis of the Personal Year Number and the theme for the current year.'),
  }),
  luckyElements: z.object({
    luckyNumbers: z.array(z.number()).describe("A list of lucky numbers for the person."),
    luckyColor: z.string().describe("A lucky color associated with the person's numbers."),
    luckyDay: z.string().describe("A lucky day of the week."),
    luckyGemstone: z.string().describe("A lucky gemstone recommendation."),
  }),
  careerSuggestions: z.string().describe("Career suggestions based on the numerology report."),
  relationshipCompatibility: z.string().describe("A brief on relationship compatibility based on the numerology report."),
  overallAnalysis: z.string().describe('A detailed, comprehensive analysis combining all the numerological aspects.'),
});
export type AiNumerologyAnalysisOutput = z.infer<typeof AiNumerologyAnalysisOutputSchema>;

export async function aiNumerologyAnalysis(input: AiNumerologyAnalysisInput): Promise<AiNumerologyAnalysisOutput> {
  return aiNumerologyAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiNumerologyAnalysisPrompt',
  input: {schema: AiNumerologyAnalysisInputSchema},
  output: {schema: AiNumerologyAnalysisOutputSchema},
  config: {
    temperature: 0.6,
  },
  prompt: `You are an expert numerologist. Analyze the numerology of the person based on their name and date of birth. Your response MUST be insightful and specific to the details provided, not generic.

You MUST provide the entire analysis in the following language: {{{language}}}

Name: {{{name}}}
Date of Birth: {{{dateOfBirth}}}
Current Year: ${new Date().getFullYear()}

Calculate all of the following numerology numbers and elements. Be thorough and accurate in your calculations.
For each of the core numbers (Life Path, Destiny, Soul Urge, Personality, Birth Day, Maturity, Personal Year), provide both the number and a detailed, personal analysis of what that number means for this specific individual. Avoid templated answers and provide practical, encouraging advice.

- Life Path Number (from Date of Birth)
- Destiny/Expression Number (from Full Name)
- Soul Urge Number (from vowels in Full Name)
- Personality Number (from consonants in Full Name)
- Birth Day Number (from the day of birth)
- Maturity Number (Life Path + Destiny Number)
- Personal Year Number (from DOB + Current Year)
- Lucky Elements (Numbers, Color, Day, Gemstone)
- Career Suggestions based on the numbers.
- Relationship Compatibility summary.
- A final, overall summary analysis combining all these aspects.

Provide the full analysis in the structured JSON format as requested.
`, 
});

const aiNumerologyAnalysisFlow = ai.defineFlow(
  {
    name: 'aiNumerologyAnalysisFlow',
    inputSchema: AiNumerologyAnalysisInputSchema,
    outputSchema: AiNumerologyAnalysisOutputSchema,
  },
  async input => {
    const {output} = await prompt({
        ...input,
        language: input.language || 'English',
    });
    return output!;
  }
);
